### ISSUE TITLE
Possibly already exists

### ISSUE THREAD

**Issue by boshek** [steffilazerte/envirocan#1]
A fairly well developed package already exists over at https://github.com/gavinsimpson/canadaHCD

**Comment by steffilazerte** [comment]
Thanks for the info, looks like we were developing our packages side by side almost at the same time (although they were probably a month or two ahead of me).

I wouldn't stop or remove `envirocan` now, though, because it is nearly fully developed. I'd say it was fully developed, but it hasn't had enough use for me to be confident that there are no bugs left, and I definitely need to test the interpolations some more. 

I'd argue that it looks like `envirocan` might be slightly more userfriendly, but I'd have to compare them more closely. It'll also be nice to see how canadaHCD develops as it looks like they're more active right than I am now.
